name: Default
on:
  workflow_dispatch:
    inputs:
      extraVersion:
        description: "Extra version"
        required: false
      filter:
        description: "Filtering rule"
        required: false
      onlyLastNVersions:
        description: "Only run against the last N versions"
        default: "1"
        required: true
      numRuns:
        description: "Number of runs"
        default: "100"
        required: true
      numIterations:
        description: "Number of iterations"
        default: "100"
        required: true
      enablePropertyMode:
        description: "Run synchronous properties"
        type: boolean
        default: true
      enableAsyncPropertyMode:
        description: "Run asynchronous properties"
        type: boolean
        default: false
      enablePropertyNoInitMode:
        description: "Run synchronous properties (without init)"
        type: boolean
        default: false
      enablePropertyNoInitModeSingle:
        description: "Run synchronous properties once (without init)"
        type: boolean
        default: false
      enableInitMode:
        description: "Initialize the arbitrary"
        type: boolean
        default: false
jobs:
  benchmark:
    name: "Benchmark"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Using Node v20.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Package and Install main dependency
        run: |
          git clone --depth 1 https://github.com/dubzzz/fast-check.git
          npm install -g pnpm
          cd fast-check
          pnpm install
          pnpm run build:all
          pnpm run pack:all
          mv packages/fast-check/package.tgz fast-check.tgz
          cd ..
          npm install fc-99.99.98@./fast-check/fast-check.tgz
          npm install fc-99.99.99@./fast-check/fast-check.tgz
      - if: github.event.inputs.extraVersion != ''
        name: Install extra dependency
        run: npm install fc-99.99.99@${{github.event.inputs.extraVersion}}
      - name: Run benchmark
        run: |
          export EXTRA_VERSION="${{github.event.inputs.extraVersion}}"
          export FILTER="${{github.event.inputs.filter}}"
          export LAST_N_VERSIONS="${{github.event.inputs.onlyLastNVersions}}"
          export NUM_RUNS="${{github.event.inputs.numRuns}}"
          export NUM_ITERATIONS="${{github.event.inputs.numIterations}}"
          export ENABLE_PROPERTY_MODE="${{github.event.inputs.enablePropertyMode}}"
          export ENABLE_ASYNC_PROPERTY_MODE="${{github.event.inputs.enableAsyncPropertyMode}}"
          export ENABLE_PROPERTY_NO_INIT_MODE="${{github.event.inputs.enablePropertyNoInitMode}}"
          export ENABLE_PROPERTY_NO_INIT_MODE_SINGLE="${{github.event.inputs.enablePropertyNoInitModeSingle}}"
          export ENABLE_INIT_MODE="${{github.event.inputs.enableInitMode}}"
          npm run test
