name: Default
on:
  workflow_dispatch:
    inputs:
      extraVersion:
        description: "Extra version"
        required: false
jobs:
  benchmark:
    name: "Benchmark"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Using Node v16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Package and Install main dependency
        run: |
          git clone --depth 1 https://github.com/dubzzz/fast-check.git
          cd fast-check
          yarn
          yarn build:prod-ci
          yarn pack
          mv fast-check-*.tgz fast-check.tgz
          cd ..
          npm install fc-99.99.98@./fast-check/fast-check.tgz
          npm install fc-99.99.99@./fast-check/fast-check.tgz
      - if: github.event.inputs.extraVersion != ''
        name: Install extra dependency
        run: npm install fc-99.99.99@${{github.event.inputs.extraVersion}}
      - name: Run benchmark
        run: |
          export EXTRA_VERSION="${{github.event.inputs.extraVersion}}"
          npm run test
