name: Quick
on:
  pull_request:
    branches:
      - main
jobs:
  benchmark:
    name: "Benchmark"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Using Node v16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Package and Install main dependency
        run: |
          git clone --depth 1 https://github.com/dubzzz/fast-check.git
          cd fast-check
          yarn
          yarn build:all
          yarn pack:all
          mv packages/fast-check/package.tgz fast-check.tgz
          cd ..
          npm install fc-99.99.98@./fast-check/fast-check.tgz
          npm install fc-99.99.99@./fast-check/fast-check.tgz
      - name: Run benchmark
        run: npm run test:quick
